### ISSUE TITLE
Error installed PythonEmbedInR on Silicon Mac

### ISSUE THREAD

**Issue by apratap** [Sage-Bionetworks/PythonEmbedInR#103]
Hey Folks - The issue is related to the installation of `synapser` on the new silicon chip. Any workaround? 

Thanks!
-Abhi

`R CMD INSTALL PythonEmbedInR-0.7.84.tar.gz`

configure: error: Unexpected output of 'arch' on OSX

**Comment by thomasyu888** [comment]
Closing as this package is now archived
