### ISSUE TITLE
Can't install packages on HPC cluster

### ISSUE THREAD

**Issue by jbryois** [Sage-Bionetworks/PythonEmbedInR#96]
I can't install this Package on our HPC cluster, even if I specify the location for the install:

`install.packages("PythonEmbedInR", repos=c("http://cran.fhcrc.org", "http://ran.synapse.org"),lib = '~/R/x86_64-pc-linux-gnu-library/3.6.1-foss/')`

`checking build system type... mkdir: cannot create directory '/local/34569166/cg179410-25209': No such file or directory
mkdir: cannot create directory '/local/34569166/cg-179410': No such file or directory
config.guess: cannot create a temporary directory in /local/34569166
configure: error: cannot guess build type; you must specify one
ERROR: configuration failed for package ‘PythonEmbedInR’`

Works fine on my local machine.

Any way to install it on our HPC cluster?
Thanks!

**Comment by thomasyu888** [comment]
Closing as archived
